sudo: required
language: node_js
node_js:
    - 9
env:
    - DOCKER_REPO=gorillab/reader-scraper
jobs:
    include:
        -
            stage: test
            install: [yarn]
            script: ['yarn test']
        -
            stage: build
            services: [docker]
            script: ['docker build -t "$DOCKER_REPO" .', "if [ ! -z \"$TRAVIS_TAG\" ]; then docker login -u \"$DOCKER_USERNAME\" -p \"$DOCKER_PASSWORD\";\nfor TAG in {\"$TRAVIS_TAG\",latest}; do docker tag \"$DOCKER_REPO\" \"$DOCKER_REPO\":\"$TAG\";\ndocker push \"$DOCKER_REPO\":\"$TAG\"; done fi"]
cache:
    yarn: true
    directories:
        - node_modules
notifications:
    email: false
    slack:
        secure: EDs9WAwAIUv46UDr5edcYZi4oTHoOzZW0e8j1JLWgBZhXZbUlILRu0xJLc9BXYu/a9Jw3mSZeJlJDfFGECaYvGClNA+O6xvP/YI1rwTW+vaTOuEfMm2LFiGWVpmRfNDhm+X5UpfdQHxwGxDgb7cZafUpPlgkv+pT0hlN4TPFTgqVsganVz9B6UWgY1o0NUai+4c8QHWhrjRRIiUoRCdkMBZVd9s9mGm1ZOGmf64UggQ8IQO2TBZaK0vUTesxf4//84GkgrzeiUCb9/DgeH/WB5/xvlNTCuUxEOEdt/eLfFCOagJB3SzJ2PkHeYSAFjiN4O1h30LbzRF/6FO8N0KbMED3jvOB0gL88A6E0Jh7IxtJZppR32eSDrN79Co2N1AWkiVBtaCLtYXudd5DM/X0x4WGdGNYQ1ZppyRE3CiwZ69e8YjPN6/Bv1NWaEfJW3VL/vTdBwqzTpufhdYTNHweBz92gqFRpJ9Um0fmLGLaaRGqN9AK+ZFVkzfe8P3TzobcC7KA9cpHa4GLWfeknDa9ywUn91obBxLc9SW9/p4OJT+Dn9gji85s+n41640/nJl7CqG2dpOo8p2BChNLKivL8O5DSHr0/Yk5OZRmwVwgGxJJOlYXCgAF0pmTvOgWe+r1uh2BHXSg2dJWhEwRz6UO5qFvbDvI6naGDXk/m09SkNE=
        on_pull_requests: false
