language: node_js

node_js:
  - 6
  - 7
  - 8

install:
  - yarn

cache:
  yarn: true
  directories:
  - node_modules

script:
  - yarn build

deploy:
  provider: npm
  email: "hello@gorillab.co"
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  on:
    node: '8'
    branch: master
    tags: true

notifications:
  email: false
  slack:
    secure: xaRgHkIx6ocSkG1uh80w4/pt1vZ7pvzW58TL9/dUjndK4SF2HvY1rbgAmtGXrLRC+8bA0svjR1zwvruW1IBomXjGoqQPahr8wGMJf5geA3PcM96CagxB0uPp1kL6uKVTl54fVzg2KHBrThqTc8pici/RtAWlLLjAr6hlXAvNoBz501Jn0Vd/P6MM29ilmR4IIkwIaQRAIImBCOD46eoIT3M4B4hRQD58CF7XsB1D89AocrwmPPosTIM4gUhnY+SgjafEeVUUjpPWnMPS6hh/qBKJMpBsYi8hRkYy0Qi/jONEgJnADVSdYBL0ppcCwmVaE3C37N1I4Nr6GGOWl1I/oKSlBdoTqTSYMV4gD6k8JJJkMgWAo75QJ3vpZNl73KjhrkAJIPCtqtQMrnOhDKGv/FDup5lIR7hebwaZEJvBWjEyby/7n2/GpE7GE7hDHladAQ52X2rJqNq5ObsH32gEtlroAtJtrdIric1/+ucvXb6TjEQf1RwB2f8MafCG4+b/NvroQ3hqixpV25+aGSV/o+snkoBe0oyBz524sPUY34vgv0jtQZPJ5MPnkuqh4Lmv++G0xqWIjxAo82pwWUK375d3WCpHfz84EzZzgjPhhP3AVuJej7itRkIGiIYtZb0abd0FyWbnqulsIaaV/Yl1ZIP0jLfSE+7B9ZR87RApM60=
